FROM ubuntu:24.04

RUN apt-get update 

RUN apt-get -y install \
python3-pip \
python3-packaging \
git \
pv

#RUN pip3 install --break-system-packages --upgrade pip


RUN pip install --break-system-packages west

RUN mkdir /scripts

VOLUME /artifacts

COPY  download.sh /scripts/download.sh

CMD ["/scripts/download.sh", "2404"]
